# Generated by Django 5.2.7 on 2025-11-24 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Programming', 'Programming'), ('Frontend', 'Frontend Development'), ('Backend', 'Backend Development'), ('FullStack', 'Full Stack Development'), ('Mobile', 'Mobile Development'), ('DevOps', 'DevOps & Cloud'), ('DataScience', 'Data Science'), ('MachineLearning', 'Machine Learning'), ('UIUX', 'UI/UX Design'), ('ProductManagement', 'Product Management'), ('QA', 'Quality Assurance'), ('Cybersecurity', 'Cybersecurity'), ('CloudComputing', 'Cloud Computing'), ('Blockchain', 'Blockchain'), ('GameDev', 'Game Development')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Quiz Categories',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Mixed', 'Mixed')], default='Mixed', max_length=20)),
                ('questions', models.JSONField()),
                ('questions_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField(default=10)),
                ('correct_answers', models.IntegerField()),
                ('answers', models.JSONField()),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('improvement_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.questionset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='interviews__user_id_51684d_idx'), models.Index(fields=['user', '-created_at'], name='interviews__user_id_ce548b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action', 'window_start'], name='interviews__user_id_e04806_idx')],
                'unique_together': {('user', 'action', 'window_start')},
            },
        ),
    ]
